name: Swift MacOS

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  macOS-xcode:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        xcode_version: [11.3.1, 11.4, 12.2]
        # xcode version is used to change swift version
        # xcode 11.3.1 == swift 5.1.3
        # xcode 11.4 == swift 5.2.2
        # xcode 12.2 == swift 5.3.1
    steps:
    - uses: actions/checkout@v2
    - name: Xcode Version
      run: |
        sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode_version }}.app
        xcodebuild -version
    - name: Swift Version
      run: swift --version
    - name: Build
      run: swift build
    - name: Test
      run: swift test --enable-test-discovery
